### ISSUE TITLE
Add options to customize test runs

### ISSUE THREAD

**Issue by fesor** [fesor/behat-concurrency#2]
in case of expensive precondition in background (or prepared in hooks in case of outline scenarios) and light scenarios, it would be better to execute entire feature or outline scenario in single worker. To make it possible this extension should provide configuration option to:
- disable scenario parallelization 
- disable outline scenario parallelization

Example:

```
Fesor\Behat\Concurrency:
    parallelization:
        scenario: false # whole feature per worker
        outline: false # whole outline per worker
```
